name: 'Cards Jekyll Theme V2'
description: 'Responsive Column Cards'
baseurl: ''
url: 'https://mohamadrido.github.io/grid-jekyll-theme'
author: 'Mohamad Rido'
email: 'mohamad.rido@yandex.com'
permalink: /:title
plugin:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
paginate: 9
